name: rawfilepath
version: 1.1.1
synopsis: Use RawFilePath instead of FilePath
description: A fast and safe API with high-level features on `RawFilePath`, instead of `FilePath`, to avoid the encoding issues or performance penalties. Please see `README.md`
category: System
author: XT et al.
maintainer: git@xtendo.org
copyright: (C) 2016-2024 XT et al.
license: Apache-2.0
github: xtendo-org/rawfilepath
extra-source-files:
- README.md
dependencies:
- bytestring
library:
  source-dirs: src
  c-sources:
  - cbits/runProcess.c
  - cbits/processFlags.c
  - cbits/processFlags.h
  default-extensions:
  - BangPatterns
  - CPP
  - LambdaCase
  - OverloadedStrings
  - RecordWildCards
  include-dirs:
  - cbits
  exposed-modules:
  - Data.ByteString.RawFilePath
  - RawFilePath
  - RawFilePath.Directory
  - RawFilePath.Process
  dependencies:
  - base >= 4.7 && < 5
  - unix
tests:
  RawFilePath-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - rawfilepath
