name: Haskell CI

on: [push, pull_request]

jobs:
  stacktest:
    name: stack test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/setup@v2
        with:
          ghc-version: '9.6.3'
          enable-stack: true
          stack-version: 'latest'
      - run: stack test
